name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this
        # @see https://github.com/actions/checkout
        uses: actions/checkout@v3
            
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run install
        # @see https://github.com/marketplace/actions/setup-pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]

      - name: Deploy to GitHub Pages
        # @see https://github.com/crazy-max/ghaction-github-pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 docs 分支
          target_branch: docs
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist


